language: c
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev python-pip python-yaml g++
    - sudo pip install conda
    - sudo conda init
    - conda create --yes --name test numpy scipy pytables numexpr nose pandas cython statsmodels pandas patsy pyyaml matplotlib pip
    - export PATH="$HOME/envs/test/bin/:$PATH"
    - pip install -q fastcluster mdtraj git+git://github.com/rmcgibbo/simtk.unit
    
script:
    - python setup.py install
    - nosetests -vv tests-nose/test_testsystems.py
