language: c
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev python-pip python-yaml g++
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpcre3 libpcre3-dev gromacs
    - sudo apt-get install -qq swig doxygen
    - sudo pip install conda
    - sudo conda init
    - conda create --yes --name test numpy scipy pytables numexpr nose pandas cython statsmodels pandas patsy pyyaml matplotlib pip
    - export PATH="$HOME/envs/test/bin/:$PATH"
    - pip install -q fastcluster mdtraj git+git://github.com/rmcgibbo/simtk.unit
    
script:
    - cmake -DCMAKE_INSTALL_PREFIX=~/OpenMM .
    - make
    - make install
    - ls ~/OpenMM/include
    - export LD_LIBRARY_PATH=~/OpenMM/lib/
    - export OPENMM_LIB_PATH=~/OpenMM/lib/
    - export OPENMM_INCLUDE_PATH=~/OpenMM/include/
    - cd python
    - sudo -E python setup.py install
    - cd tests
    - nosetests -vv
    - python setup.py install
    - nosetests -vv tests-nose/test_testsystems.py
