language: c
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev python-pip python-yaml g++
    - sudo apt-get install -qq libpcre3 libpcre3-dev gromacs
    - sudo apt-get install -qq swig doxygen
    - sudo pip install conda
    - sudo conda init
    - conda create --yes --name test numpy scipy pytables numexpr nose pandas cython statsmodels pandas patsy pyyaml pip netCDF4 pyflakes
    - export PATH="$HOME/envs/test/bin/:$PATH"
    - conda config --add channels http://conda.binstar.org/rmcgibbo
    - conda install openmm
    - pip install pymbar
    - pip install -q mdtraj git+git://github.com/rmcgibbo/simtk.unit
    
script:
    - python setup.py install
    - nosetests tests-nose/test_testsystems.py

after_script:
    - pyflakes repex/*.py
